### ISSUE TITLE
Profile error

### ISSUE THREAD

**Issue by Nickito12** [ningirsu/stepmania-server#2]
I'm trying to run this on win 7 64 bit with python 3.5(i also tried 3.4) and im getting an error:
In profile.py line 5:
lib/cProfile.py line 22:
run__doc__ = _pyprofile.run__doc__
AttributeError: module 'profile' has no attribute 'run'

Screenshot from windows's cmd:
![pyerror](https://cloud.githubusercontent.com/assets/24706838/22630346/38201316-ebd7-11e6-806f-d3e9aab50347.png)

**Comment by ningirsu** [comment]
Ok it seems to be a name conflict:  http://stackoverflow.com/questions/16006602/cannot-import-the-cprofile-module-in-python-3

I push a fix
